name: CI/CD Pipeline

on:
  push:
    branches:
      - test6
  pull_request:
    branches:
      - test6
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.0

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Output github.ref for debugging
      run: echo "github.ref in test job is ${{ github.ref }}"

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Output github.ref for debugging
      run: echo "github.ref in publish job is ${{ github.ref }}"

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/parcel-app:${{ github.ref_name }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/parcel-app:${{ github.ref_name }}
