name: CI/CD Pipeline

on:
  push:
    branches:
      - twelve
  pull_request:
    branches:
      - twelve
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.0

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      run: echo "Checking out code"

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "Logging in to DockerHub"

    - name: Build Docker image
    run: |
      docker build -t ${{ secrets.DOCKER_USERNAME }}/parcel-app:${{ github.ref_name }} .
      echo "Docker image built"

    - name: Push Docker image
    run: |
      docker push ${{ secrets.DOCKER_USERNAME }}/parcel-app:${{ github.ref_name }}
      echo "Docker image pushed"
